// app/layout.tsx
import { ReactQueryProvider } from "@/context/react-query";
import "./globals.css";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Intro to Next.js 13 | HELHa",
  description: "Generated by create next app",
  authors: [{ name: "Nicolas Toffolo" }],
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <ReactQueryProvider>
        <body>{children}</body>
      </ReactQueryProvider>
    </html>
  );
}
